networks:
  sentiric-net:
    name: ${NETWORK_NAME:-sentiric-net}
    driver: bridge

services:
  telephony-gateway:       

      build:
        context: .
        dockerfile: Dockerfile
        args:
          SERVICE_NAME: sentiric-task-service

      env_file: 
        - ./.env

      # volumes:
      #   - ../sentiric-infrastructure/tls/certs:/etc/sentiric/tls:ro
      # devices:
      #   - "/dev/dahdi:/dev/dahdi"
      # ports:
      #   - "${TELEPHONY_GATEWAY_SERVICE_PORT}:${TELEPHONY_GATEWAY_SERVICE_PORT}"

      networks:
        - sentiric-net
      
      profiles:
        - default
        - ai

      restart: always